### ISSUE TITLE
Проблема

### ISSUE THREAD

**Issue by Dogrundiy** [Nich1con/microReader#8]
Я при первой настройке вай-фай мода, установил не тот вампир фай. А сейчас он не даёт зайти в настройки, пишет ошибку,  вместо имени сети пишет любые знаки от { до #. Помогите это исправить пожалуйста

**Comment by Dogrundiy** [comment]
> Я при первой настройке вай-фай мода, установил не тот вай фай. А сейчас он не даёт зайти в AP мод, пишет ошибку, вместо имени сети пишет любые знаки от { до #. Помогите это исправить пожалуйста

**Comment by LogExE** [comment]
Поищи переменную с ключем в коде прошивки, попробуй поменять ее значение и перепрошить читалку. Настройки сбросятся

**Comment by LogExE** [comment]
EE_KEY которая

**Comment by Nich1con** [comment]
В версии прошивки 1.1 добавлена защита от подобных ситуаций. Новая прошивка доступна уже сейчас - обновляйтесь.

**Comment by ivan87298** [comment]
у меня возникла проблема с компиляцией все попробовал ничего не помогло

default_encoding:       cp1251
Assume aggressive 'core.a' caching enabled.
Clean build, created dir core
Note: optional global include file 'C:\Users\riaby\OneDrive\������� ���\a-microReader-v1.2\a-microReader-v1.2.ino.globals.h' does not exist.
  Read more at https://arduino-esp8266.readthedocs.io/en/latest/faq/a06-global-build-options.html

*** Traceback (most recent call last):
  File "C:\Users\riaby\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2/tools/mkbuildoptglobals.py", line 824, in <module>
    rc = main()
  File "C:\Users\riaby\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2/tools/mkbuildoptglobals.py", line 819, in main
    handle_error(0)   # commit print buffer
  File "C:\Users\riaby\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2/tools/mkbuildoptglobals.py", line 274, in handle_error
    print(msg_print_buf, file=fd, end='', flush=True)
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\cp866.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u0456' in position 233: character maps to <undefined>

exit status 1
Помилка компіляції для плати Generic ESP8266 Module.
